name: Build Linux
on: [ push ]
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: clang-tidy
        uses: HorstBaerbel/action-clang-tidy@1.2
        with:
          scandir: '.'
          buildir: 'build'
          extensions: 'c,h,C,H,cpp,hpp,cc,hh,c++,h++,cxx,hxx'
        
