name: Build Linux
on: [ push ]
jobs:
  Build-Test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build project
        shell: cmd
        run: build.ps1
