name: Build Linux
on: [ push ]
jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: c-linter
        uses: github/super-linter@v4
        env:
          VALIDATE_CPP: true
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
        
